### ISSUE TITLE
Move to service

### ISSUE THREAD

**Issue by xandrck** [yarovidze/cback.club#84]
https://github.com/yarovidze/cback.club/blob/a4e1a772d3e481b992fee1a8ff221736a4bb8b39/app/controllers/admins_controller.rb#L22

Нужно вынести в отдельный сервис (так не годиться)
Тогда не нужно будет вот эти рекваеры делать в контроллере https://github.com/yarovidze/cback.club/blob/master/app/controllers/admins_controller.rb#L5	

Можно сделать `admit_service.rb`
который будет включать в себя 
`def autorisation` и `def get_action_data` методы

**Comment by OleStan** [comment]
Переніс, але все одно відповідь записую в кукі, можливо є кращий спосіб?
