### ISSUE TITLE
Open credentials

### ISSUE THREAD

**Issue by xandrck** [yarovidze/cback.club#85]
https://github.com/yarovidze/cback.club/blob/a4e1a772d3e481b992fee1a8ff221736a4bb8b39/app/controllers/admins_controller.rb#L29

Вот этого не должно вообще быть в коде все ключи должны быть вынесены в ENV переменную чтобы просечивать их на сервере, потому что на данный момент доступ к вашим кредам есть у всех.

**Comment by OleStan** [comment]
Сховав` client_id` `client_secret` замінив токен на Base64.strict_encode64(client_id + ':' + client_secret)
