### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by xandrck** [yarovidze/cback.club#88]
https://github.com/yarovidze/cback.club/blob/a4e1a772d3e481b992fee1a8ff221736a4bb8b39/app/controllers/admins_controller.rb#L63

Тут не ясно - `action.each do |client|` ?

Судя по логике тут должно быть `clents.each do |client|` не ясно с чем работаем и что сюда приходит

`client['subid'] = '1' if client['subid'] == '4'` 
очень странный поиск, может можно искать по имейлу или чему-то ещё (если речь и заприсеченных данных)
ну или `.first` как вариант

Ну и в целом всё что происходит в этом экшене должно быть в сервисе, так как тут кучу всего создаётся.

**Comment by OleStan** [comment]
```
client['subid'] = '1' if client['subid'] == '4'
очень странный поиск, может можно искать по имейлу или чему-то ещё (если речь и заприсеченных данных)
ну или .first как вариант
```

проблема в тому що покупка була зроблена з id 4, тому з сервісу приходить відповідь з id = 4. В нормальній ситуації якщо такого id нема і нашій то ми пропускаємо. Але це єдина реальна покупка була тому щоб хоч щось бачити прийшлось міняти id з 4 на 1 щоб бачити що ми отримуємо відповідь з сервісу.

**Comment by OleStan** [comment]
`Ну и в целом всё что происходит в этом экшене должно быть в сервисе, так как тут кучу всего создаётся.`
Пробував ну тоді сервісу прийдеться наслідувати клас контролера для роботи з params
