### ISSUE TITLE
Error handler

### ISSUE THREAD

**Issue by xandrck** [yarovidze/cback.club#90]
https://github.com/yarovidze/cback.club/blob/a4e1a772d3e481b992fee1a8ff221736a4bb8b39/app/controllers/admins_controller.rb#L114
Метод зависит от данных которые возвращает сторонняя либа, но у нас нету обработок ошибок, нужно добавить иначе если что-то пойдёт не так приложение будет просто крашиться

**Comment by OleStan** [comment]
добавив умову
